### ISSUE TITLE
Sample doesn't compile

### ISSUE THREAD

**Issue by seanrockster** [macsux/builder-pattern-generator#1]
Hi 

This looks interesting however the Sample project doesn't compile.

CS0117	'Person' does not contain a definition for 'Builder'	Sample	master\Sample\Program.cs	24

Regards
Sean

**Comment by macsux** [comment]
You need to have dotnet 5 installed and compile with visual studio 2019
preview

**Comment by seanrockster** [comment]
ok i'll have a look.
